### ISSUE TITLE
After running, I heard the sentence that it started, and then I reported this error

### ISSUE THREAD

**Issue by phpoh** [ShaunLinTW/Voice_Assistant_Jarvis_Based_on_ChatGPT_API#1]
File "C:\Python\lib\site-packages\speech_recognition\__init__.py", line 120, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\voice\Jarvis.py", line 58, in <module>
    prompt = listen()
  File "C:\Users\Administrator\Desktop\voice\Jarvis.py", line 33, in listen
    with sr.Microphone() as source:
  File "C:\Python\lib\site-packages\speech_recognition\__init__.py", line 92, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Python\lib\site-packages\speech_recognition\__init__.py", line 122, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by ShaunLinTW** [comment]
You need to install pyaudio library, you can try "pip install pyaudio" in your command terminal.
If it doesn't work, you can try to download the official package directly for your python version from this website https://pypi.org/project/PyAudio/#files

**Comment by phpoh** [comment]
Oh, yes, thank you! I'll try

**Comment by phpoh** [comment]
Run after installation：


C:\Users\Administrator\Desktop\voice>pip install pyaudio
Collecting pyaudio
  Downloading PyAudio-0.2.13-cp310-cp310-win_amd64.whl (164 kB)
     ---------------------------------------- 164.1/164.1 kB 410.2 kB/s eta 0:00:00
Installing collected packages: pyaudio
Successfully installed pyaudio-0.2.13

C:\Users\Administrator\Desktop\voice>python Jarvis.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\voice\Jarvis.py", line 58, in <module>
    prompt = listen()
  File "C:\Users\Administrator\Desktop\voice\Jarvis.py", line 33, in listen
    with sr.Microphone() as source:
  File "C:\Python\lib\site-packages\speech_recognition\__init__.py", line 99, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "C:\Python\lib\site-packages\pyaudio\__init__.py", line 812, in get_default_input_device_info
    device_index = pa.get_default_input_device()
OSError: No Default Input Device Available

**Comment by phpoh** [comment]
Can I use Chinese? My hero

**Comment by ShaunLinTW** [comment]
I didn't try that before, you can try it.
